const APPOINTMENT_STATUS_VALUES = Object.freeze({
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
});

const APPOINTMENT_STATUSES = Object.freeze(Object.values(APPOINTMENT_STATUS_VALUES));

module.exports = {
  APPOINTMENT_STATUS_VALUES,
  APPOINTMENT_STATUSES,
};
