const ROLE_VALUES = Object.freeze({
  CUSTOMER: 'CUSTOMER',
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
  BRANCH_MANAGER: 'BRANCH_MANAGER',
  OPTOMETRIST: 'OPTOMETRIST',
  MANAGEMENT: 'MANAGEMENT',
  SALES_ASSISTANT_CASHIER: 'SALES_ASSISTANT_CASHIER',
});

const CUSTOMER_ROLE_VALUES = Object.freeze([ROLE_VALUES.CUSTOMER]);
const STAFF_ROLE_VALUES = Object.freeze([
  ROLE_VALUES.INVENTORY_MANAGER,
  ROLE_VALUES.BRANCH_MANAGER,
  ROLE_VALUES.OPTOMETRIST,
  ROLE_VALUES.MANAGEMENT,
  ROLE_VALUES.SALES_ASSISTANT_CASHIER,
]);
const ADMIN_ROLE_VALUES = Object.freeze([ROLE_VALUES.SYSTEM_ADMIN]);

module.exports = {
  ROLE_VALUES,
  CUSTOMER_ROLE_VALUES,
  STAFF_ROLE_VALUES,
  ADMIN_ROLE_VALUES,
};
